### ISSUE TITLE
Barcode scanner

### ISSUE THREAD

**Issue by timnilnil** [iceteagroup/wisej-examples#93]
We are using barcode scanner control on our mobile app. One of our user is having issue with barcode scanner. instead of seeing camera he only see blank screen. Image of his screen is attached.
 
My questions is what is the minimum iOS version that will allow user to use barcode scanner? The user that is having issue has iOS version of 14.2. Most of the users are not having issue.

Attached is the screen shot of his device properties. 

Thanks
Nilesh Sheth
Poet Biofuels
![Steven Gusa Device Properties](https://user-images.githubusercontent.com/71887507/177787967-57f4828d-6b64-46bb-8e0e-a49c50f48bb8.png)
![Steven Gusa Barcode scanner screen](https://user-images.githubusercontent.com/71887507/177787985-e2481fa0-cf77-48e8-95fe-0001c326349c.png)

**Comment by LRufenacht** [comment]
Hi @timnilnil,

It looks like support for using the in-browser camera (using getUserMedia) was added in iOS v14.3:
https://bugs.webkit.org/show_bug.cgi?id=208667

HTH,
Levie
