### ISSUE TITLE
Wisej.Framework

### ISSUE THREAD

**Issue by LauraCaraza** [iceteagroup/wisej-examples#95]
Hi, I'm trying to run the ChartJS example but Visual Study Community 2022 says it cannot load file or assembly 'Wisej.Framework' or one of its dependencies. I don't find it neither. Any suggestions?

**Comment by AlaaTrAce** [comment]
Hi @LauraCaraza ,

Can you please let us know what branch you're using?

Best,
Alaa

**Comment by LauraCaraza** [comment]
I'm new to this and I don't know exactly what you mean, but I'm using Wisej-3 (3.2.4) and Wisej-3-ChartJS (3.2.4), as well as net48 and net6.0. I loaded packages Microsoft.NETFramework.ReferenceAssemblies and Microsoft.NETFramework.ReferenceAssemblies.net481 and the first error disappeared . Now I have the errors: "'Global.System.Web.HttpRequest' is not defined", "'Global.System.Web.HttpResponse' is not defined", "'Global.System.Web.HttpContext' is not defined" and "'HttpContext' is not a member of 'System.Web'."
